# Generated by Django 4.0.2 on 2022-02-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation_date', models.DateField()),
                ('topic', models.CharField(max_length=50)),
                ('multi_person', models.BooleanField()),
            ],
            options={
                'ordering': ['presentation_date'],
            },
        ),
    ]
