# Generated by Django 4.0.2 on 2022-02-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiclist',
            name='note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
